services:

  # Frontend (Nuxt + Nginx)
  frontend:
    build:
      context: ./frontend  # Korrektes Verzeichnis für das Frontend
    container_name: frontend_nginx
    image: nginx:latest
    ports:
      - "8080:80"
      - "443:443"
    networks:
      - app-network
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - nuxt 
      - backend 
    
  nuxt:
    build: ./app/
    restart: always
    ports:
      - "3000:3000"
    command:
      "npm run start"

  # Backend (Node.js API mit Prisma)
  backend:
    build: ./backend  # Korrektes Verzeichnis für das Backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/src/app
    networks:
      - app-network
    depends_on:
      - db
    env_file:
      - .env

  # MySQL Datenbank
  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    env_file:
      - .env

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
    driver: local